services:
  - type: web
    name: gamer-xmd-session
    env: node
    build:
      node:
        version: 18.x
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://vador2899:ukSP9PH0BVBA3Yvh@cluster0.qdylypu.mongodb.net/?retryWrites=true&w=majority
      - key: SESSION_KEY
        generateValue: true
      - key: BOT_NAME
        value: GAMER-XMD
    healthCheckPath: /health